//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoAktarim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_CS_ST_COURSE
    {
        public AL_CS_ST_COURSE()
        {
            this.AL_CS_ST_GROUP = new HashSet<AL_CS_ST_GROUP>();
        }
    
        public System.Guid COURSEID { get; set; }
        public System.Guid PROGRAMID { get; set; }
        public Nullable<System.Guid> MCOURSEID { get; set; }
        public Nullable<System.Guid> TERMID { get; set; }
        public string COURSENAME { get; set; }
        public string COURSECODE { get; set; }
        public byte ENROLLMENTTYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PASSINGSCORE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string TEXTFIELD1 { get; set; }
        public string TEXTFIELD2 { get; set; }
        public string TEXTFIELD3 { get; set; }
        public Nullable<double> NUMBERFIELD1 { get; set; }
        public Nullable<double> NUMBERFIELD2 { get; set; }
        public Nullable<double> NUMBERFIELD3 { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public System.DateTime DATEMODIFIED { get; set; }
        public System.Guid USERCREATED { get; set; }
        public System.Guid USERMODIFIED { get; set; }
        public byte DBSTATUS { get; set; }
        public string SYNCKEY_OLD { get; set; }
        public Nullable<System.DateTime> SYNCDATE_OLD { get; set; }
        public Nullable<byte> SYNCAUTO_OLD { get; set; }
        public int ESTIMATEDDURATION { get; set; }
        public byte VIEWMODE { get; set; }
        public byte COURSETYPE { get; set; }
        public Nullable<System.Guid> LASTSYNCID_OLD { get; set; }
    
        public virtual AL_ST_PROGRAMS AL_ST_PROGRAMS { get; set; }
        public virtual ICollection<AL_CS_ST_GROUP> AL_CS_ST_GROUP { get; set; }
    }
}
