//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoAktarim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_CS_ST_GROUP
    {
        public System.Guid GROUPID { get; set; }
        public Nullable<System.Guid> COURSEID { get; set; }
        public string GROUPNAME { get; set; }
        public Nullable<byte> GROUPTYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public int MAXUSERS { get; set; }
        public Nullable<byte> PRIVACYMODE { get; set; }
        public string TEXTFIELD1 { get; set; }
        public string TEXTFIELD2 { get; set; }
        public string TEXTFIELD3 { get; set; }
        public Nullable<double> NUMBERFIELD1 { get; set; }
        public Nullable<double> NUMBERFIELD2 { get; set; }
        public Nullable<double> NUMBERFIELD3 { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public System.DateTime DATEMODIFIED { get; set; }
        public System.Guid USERCREATED { get; set; }
        public System.Guid USERMODIFIED { get; set; }
        public byte DBSTATUS { get; set; }
    
        public virtual AL_CS_ST_COURSE AL_CS_ST_COURSE { get; set; }
    }
}
