//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoAktarim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_CS_MT_ACTIVITY_GROUP
    {
        public System.Guid GROUPID { get; set; }
        public System.Guid ACTIVITYID { get; set; }
        public System.DateTime TIMEADDED { get; set; }
    }
}
