//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoAktarim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_LS_ST_LESSON
    {
        public System.Guid MCOURSEID { get; set; }
        public System.Guid ELESSONID { get; set; }
        public string LESSONNAME { get; set; }
        public string SHORTNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string DEFAULTPAGE { get; set; }
        public string LESSONTYPE { get; set; }
        public Nullable<System.Guid> PACKAGEID { get; set; }
        public byte ISSCOSCORING { get; set; }
        public string LANGUAGE { get; set; }
        public byte USEINPLANNING { get; set; }
        public string SCOIDENTIFIER { get; set; }
        public string SCOTITLE { get; set; }
        public int ESTIMATEDDURATION { get; set; }
        public string TARGETAUDIENCE { get; set; }
        public string TEXTFIELD1 { get; set; }
        public string TEXTFIELD2 { get; set; }
        public string TEXTFIELD3 { get; set; }
        public Nullable<double> NUMBERFIELD1 { get; set; }
        public Nullable<double> NUMBERFIELD2 { get; set; }
        public Nullable<double> NUMBERFIELD3 { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public System.DateTime DATEMODIFIED { get; set; }
        public System.Guid USERCREATED { get; set; }
        public System.Guid USERMODIFIED { get; set; }
        public byte DBSTATUS { get; set; }
        public string CHTOOL { get; set; }
        public Nullable<bool> CHSTATUS { get; set; }
        public string CHTITLE { get; set; }
        public bool CONVERTEDSOURCE { get; set; }
        public byte INSTALLED { get; set; }
        public string INSTALLEDMESSAGE { get; set; }
        public byte FILECHECK { get; set; }
        public string FILECHECKMESSAGE { get; set; }
    }
}
