//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoAktarim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_ST_PROGRAMS
    {
        public AL_ST_PROGRAMS()
        {
            this.AL_CS_MT_PMCOURSE = new HashSet<AL_CS_MT_PMCOURSE>();
            this.AL_CS_ST_COURSE = new HashSet<AL_CS_ST_COURSE>();
        }
    
        public System.Guid PROGRAMID { get; set; }
        public Nullable<System.Guid> SITEID { get; set; }
        public Nullable<System.Guid> CALENDERID { get; set; }
        public Nullable<byte> FEEDBACK { get; set; }
        public string PROGRAMCODE { get; set; }
        public string PROGRAMNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string EDUCATIONLANGUAGE { get; set; }
        public string DEPARTMENTCODE { get; set; }
        public string EDUCATIONTYPECODE { get; set; }
        public string PROGRAMLOGO { get; set; }
        public string PROGRAMPICTURE { get; set; }
        public string INDEXPAGEMESSAGE { get; set; }
        public string TEXTFIELD1 { get; set; }
        public string TEXTFIELD2 { get; set; }
        public string TEXTFIELD3 { get; set; }
        public Nullable<double> NUMBERFIELD1 { get; set; }
        public Nullable<double> NUMBERFIELD2 { get; set; }
        public Nullable<double> NUMBERFIELD3 { get; set; }
        public string SYNCKEY { get; set; }
        public Nullable<System.DateTime> SYNCDATE { get; set; }
        public byte SYNCAUTO { get; set; }
        public byte DBSTATUS { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public System.DateTime DATEMODIFIED { get; set; }
        public System.Guid USERCREATED { get; set; }
        public System.Guid USERMODIFIED { get; set; }
    
        public virtual ICollection<AL_CS_MT_PMCOURSE> AL_CS_MT_PMCOURSE { get; set; }
        public virtual ICollection<AL_CS_ST_COURSE> AL_CS_ST_COURSE { get; set; }
    }
}
