//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoAktarim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAUPORTDB : DbContext
    {
        public SAUPORTDB()
            : base("name=SAUPORTDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AL_CS_MT_PMCOURSE> AL_CS_MT_PMCOURSE { get; set; }
        public virtual DbSet<AL_CS_ST_COURSE> AL_CS_ST_COURSE { get; set; }
        public virtual DbSet<AL_CS_ST_MASTERCOURSE> AL_CS_ST_MASTERCOURSE { get; set; }
        public virtual DbSet<AL_LS_ST_ACTIVITY> AL_LS_ST_ACTIVITY { get; set; }
        public virtual DbSet<AL_LS_ST_LESSON> AL_LS_ST_LESSON { get; set; }
        public virtual DbSet<AL_SR_ST_SOURCE> AL_SR_ST_SOURCE { get; set; }
        public virtual DbSet<AL_ST_PROGRAMS> AL_ST_PROGRAMS { get; set; }
        public virtual DbSet<WL_LS_LESSON_CONTROL> WL_LS_LESSON_CONTROL { get; set; }
        public virtual DbSet<WL_SR_ST_TEMPLATE_2> WL_SR_ST_TEMPLATE_2 { get; set; }
        public virtual DbSet<AL_CS_MT_ACTIVITY_GROUP> AL_CS_MT_ACTIVITY_GROUP { get; set; }
        public virtual DbSet<AL_CS_ST_GROUP> AL_CS_ST_GROUP { get; set; }
    }
}
