//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoAktarim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WL_LS_LESSON_CONTROL
    {
        public Nullable<System.Guid> MCOURSEID { get; set; }
        public System.Guid ELESSONID { get; set; }
        public Nullable<System.Guid> COURSEID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string PATH { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.Guid> USERCREATED { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<System.Guid> USERMODIFIED { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public Nullable<bool> ISCONFIRM { get; set; }
        public Nullable<int> STARTWEEK { get; set; }
        public Nullable<int> ENDWEEK { get; set; }
        public Nullable<int> STARTDAY { get; set; }
        public Nullable<int> ENDDAY { get; set; }
        public string ACTIVITYNAME { get; set; }
        public Nullable<int> TEMPLATEADDED { get; set; }
        public Nullable<System.Guid> ELESSONOLDID { get; set; }
    }
}
