//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoAktarim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WL_SR_ST_TEMPLATE_2
    {
        public System.Guid TEMPLATEID { get; set; }
        public Nullable<System.Guid> MCOURSEID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string TEXTFIELD1 { get; set; }
        public string TEXTFIELD2 { get; set; }
        public string TEXTFIELD3 { get; set; }
        public Nullable<double> NUMBERFIELD2 { get; set; }
        public Nullable<double> NUMBERFIELD1 { get; set; }
        public Nullable<double> NUMBERFIELD3 { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public System.DateTime DATEMODIFIED { get; set; }
        public System.Guid USERCREATED { get; set; }
        public System.Guid USERMODIFIED { get; set; }
        public byte DBSTATUS { get; set; }
        public string SRCTYPE { get; set; }
        public string SRCURL { get; set; }
        public string SRCBODY { get; set; }
        public Nullable<System.Guid> REFID { get; set; }
        public Nullable<int> SOURCEADDED { get; set; }
    }
}
